### ISSUE TITLE
Vagrant provision script redownloads archives on each run

### ISSUE THREAD

**Issue by jameskyle** [att-innovate/charmander#6]
When rerunning the vagrant provision script, it redownloads new archives each time. E.g. go-<version>-.1.tgz, go-<version>.2.tgz, though it still references the first archive for installing.

**Comment by neuhausler** [comment]
We suggest to do a "vagrant destroy" and a "vagrant up" in those (hopefully) rare situations when a vagrant build fails. This way there is never a question in what state your images are. Will add some comment to the documentation.

**Comment by neuhausler** [comment]
added a note to the tips and tricks page
