### ISSUE TITLE
Deployment of scheduler fails

### ISSUE THREAD

**Issue by ludovicc** [att-innovate/charmander#7]
Hello,

I'm following the instruction to test charmander with Vagrant, but the second step, deploy scheduler fails. It seems that the gogoprotobuf project has migrated to Github: https://github.com/gogo/protobuf

charmander$ ./bin/deploy_scheduler
package github.com/att-innovate/charmander-scheduler
	imports code.google.com/p/gogoprotobuf/proto: unable to detect version control system for code.google.com/ path
Connection to 127.0.0.1 closed.

**Comment by neuhausler** [comment]
Thanks Claude, and yes there was an issue. Google moved packages to github which broke previous imports. It should be fixed now. Details at
https://github.com/att-innovate/charmander-scheduler/commit/d37dcdf917d90f6674513bfe527f48c2530cd1f3
